export const SCHEDULER_DASH = {
  page: 'min-h-screen bg-slate-50/80 text-slate-900',
  container: 'mx-auto flex w-full max-w-[1440px] flex-col gap-6 px-4 pb-10 pt-6 md:px-8',
  headerCard: 'rounded-3xl border border-slate-200/80 bg-white/90 shadow-sm backdrop-blur',
  headerInner: 'flex flex-col gap-4 p-4 md:p-6',
  headerTop: 'flex flex-col gap-4 md:flex-row md:items-center md:justify-between',
  titleGroup: 'flex flex-wrap items-center gap-3',
  title: 'text-2xl md:text-3xl font-semibold text-slate-900',
  badge: 'inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600',
  subtitle: 'text-sm font-medium text-slate-500',
  navGroup: 'flex flex-wrap items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-2 shadow-sm',
  navButton: 'flex h-9 w-9 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-600 transition hover:bg-slate-100',
  dateRange: 'min-w-[180px] text-center text-sm font-semibold text-slate-700',
  controlRow: 'flex flex-wrap items-center gap-3',
  controlGroup: 'flex flex-wrap items-center gap-2',
  iconButton: 'flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-600 shadow-sm transition hover:bg-slate-100',
  pillToggle: 'flex items-center rounded-full border border-slate-200 bg-slate-100 p-1 text-sm',
  pillButton: 'rounded-full px-4 py-1.5 text-sm font-semibold transition',
  pillActive: 'bg-white text-slate-900 shadow',
  pillInactive: 'text-slate-500 hover:text-slate-700',
  toolbarWrapper: 'export-hide sticky top-3 mb-4',
  selectionSummary: 'text-xs text-slate-500',
  selectionActions: 'mt-2 flex flex-wrap items-center gap-2 text-xs',
  tableWrapper: 'relative overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm',
  publishWrapper: 'mb-4 flex justify-center',
  publishButton: 'rounded-full px-6 py-2 text-sm font-semibold text-white shadow-md',
};
